### ISSUE TITLE
Animation completion will not work under some circumstances

### ISSUE THREAD

**Issue by iaomw** [icanzilb/EasyAnimation#10]
I need to remove all the animations on some layer under specific condition. But after I did something like this, it become impossible to add animation any more. How could I cancel all animation without hurt it?
```
self.spriteLayer.removeAllAnimations()
```

**Comment by icanzilb** [comment]
can you please paste in a chunk of code of how you add the animations and how you remove them so I can try to reproduce the problem?

**Comment by iaomw** [comment]
Thanks,  it something like that below. Not the same as I expected before. I will change the title. While I am touching too fast, the completion block will not work.
```
func transformToTouching() { //Response to touching event
        
    self.setHighlighted(true, animated: true)
    
    self.animationQueue.removeAll(keepCapacity: true)
    
    EAAnimationDelayed.animations.map {
        
        $0.cancelAnimationChain()
    }
    
    self.spriteLayer.removeAllAnimations()

    self.chainAnimation({ () -> Void in
            
        self.spriteLayer.fillColor = ...
        self.spriteLayer.path = ...
            
    }, duration: 0.3)
}

typealias AnimationBlock = () -> Void
typealias AnimationPiece = (animation:AnimationBlock, duration: NSTimeInterval)

var animating:Bool = false
var animationQueue = [AnimationPiece]()

func chainAnimation(animation: AnimationBlock, duration: NSTimeInterval) {
    
    self.animationQueue.append((animation:animation, duration: duration))
    
    self.feedAnimation()
}

func feedAnimation() {
    
    if self.animating {
        
        return
    }
    
    if let some = self.animationQueue.first {
        
        self.animationQueue.removeAtIndex(0)
        
        self.animating = true
        
        UIView.animateWithDuration(some.duration, delay: 0.0, options: UIViewAnimationOptions.CurveEaseInOut, animations: some.animation, completion: { (done: Bool) -> Void in // Not work while too fast
            
            self.animating = false
            
            self.feedAnimation()
        })
        
    } else {
        
        return
    } //
}
```

**Comment by icanzilb** [comment]
what I see at first sight is that you never actually use the EasyAnimation API to create chains - animateAndChainWithDuration(...). You can cancel only custom EA chains, since the "normal" animations you create with the UIKit API aren't cancelable (but not a bad idea to think if it's possible to do that). Review again the example in the README: https://github.com/icanzilb/EasyAnimation#cancel-chain-animations

**Comment by iaomw** [comment]
I really want to use your chain, but it doesn't work out while I chain them from different place. 😂
https://github.com/icanzilb/EasyAnimation/issues/9

Oops, as the block, we can comment it, it doesn't matter for the phenomenon. 😂
```
EAAnimationDelayed.animations.map {

        $0.cancelAnimationChain()
}
```
