### ISSUE TITLE
Easy Animation doesn't work with my tableView animation

### ISSUE THREAD

**Issue by reduxdj** [icanzilb/EasyAnimation#11]
installing your animation package makes this delegate not work.

func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {

**Comment by icanzilb** [comment]
are you saying that importing EasyAnimation makes a UITableView stop calling delegate methods on its delegate?

**Comment by icanzilb** [comment]
@reduxdj do you have any more details on this issue or should I close it?
