### ISSUE TITLE
Getting two errors

### ISSUE THREAD

**Issue by KuhlDesign** [icanzilb/EasyAnimation#15]
In the EasyAnimation.swift file I get two different error messages in 
"anim = RBBSpringAnimation(keyPath: pending.keyPath)
                if let anim = anim as? RBBSpringAnimation {"

1. Use of unresolved identifier 'RBBSpringAnimation'
2. Use of undeclared type 'RBBSpringAnimation'

You have a solution for this?

**Comment by icanzilb** [comment]
I need more details - no idea why you get these errors

**Comment by KuhlDesign** [comment]
I have copied the folder manually into my project, I think there these errors come from.

**Comment by icanzilb** [comment]
The RBBAnimation class is right there in the subfolder: https://github.com/icanzilb/EasyAnimation/tree/master/EasyAnimation
