### ISSUE TITLE
EasyAnimation crash in my project.

### ISSUE THREAD

**Issue by ForDrink** [icanzilb/EasyAnimation#20]
Xcode 7.1, Swift 2.0

I installed EasyAnimation via cocoapods.

When I launched my app, it stopped at:

    private static func replaceAnimationMethods() {
        //replace actionForKey
        method_exchangeImplementations(
            class_getInstanceMethod(self, "actionForKey:"),
            class_getInstanceMethod(self, "EA_actionForKey:"))
    }

* thread #2: tid = 0x278da, 0x00000001008e6c90 libswiftCore.dylib`swift_unknownRelease + 24, stop reason = EXC_BAD_ACCESS (code=1, address=0x20)

**Comment by icanzilb** [comment]
the only known crashing issue right now is when you have an opengl view in your app. other than that I can't tell what the problem can be without more details

**Comment by ForDrink** [comment]
I used SpriteKit in my project.

**Comment by icanzilb** [comment]
Than this must be the issue - using OpenGL view currently is a crashing problem. Let me know if you do find a workaround

**Comment by icanzilb** [comment]
Good news latest PR solves this :+1:
