### ISSUE TITLE
Adding EasyAnimation by Cocoapods breaks UITableView editing animation

### ISSUE THREAD

**Issue by bekkou68** [icanzilb/EasyAnimation#29]
I just add EasyAnimation v1.0.2 with Cocoapods and write no codes but it breaks UITableView editing animation.

Like this:

![2016-02-12 19 30 50](https://cloud.githubusercontent.com/assets/322852/13004523/4728912c-d1bf-11e5-8eeb-259f8122380b.png)

![2016-02-12 19 31 04](https://cloud.githubusercontent.com/assets/322852/13004528/4b5d8180-d1bf-11e5-8a6a-685747e71498.png)

![2016-02-12 19 31 18](https://cloud.githubusercontent.com/assets/322852/13004532/50796742-d1bf-11e5-9026-eac6d4ac078c.png)

I also recorded the phenomenon on movie. It occurs on iOS 9.2 on the simulator and a real device, Swift 2.0.
[broken_tableview_edit_animation.zip](https://github.com/icanzilb/EasyAnimation/files/127821/broken_tableview_edit_animation.zip)

It possibly relates to: https://github.com/icanzilb/EasyAnimation/issues/14

**Comment by icanzilb** [comment]
Interesting discovery, I will consider it in one of the next code round ups, thanks!

**Comment by bekkou68** [comment]
Thanks :D

**Comment by carayolthomas** [comment]
Hi ! Quite the same here. Somehow, when I do

`self.tableView.beginUpdates()
  self.tableView.reloadRowsAtIndexPaths([indexPath], withRowAnimation: .None)
  self.tableView.endUpdates()`

in an `UITableViewController`, the animation of the cell is buggy.

**Comment by icanzilb** [comment]
unfortunately this is one of the situations where Apple do their "magic", not quite sure how to fix it on my side

**Comment by philipengberg** [comment]
We experience the exact same issue, which is quite annoying. Isn't this another argument for considering a [non-swizzling](https://github.com/icanzilb/EasyAnimation/issues/23) version? @icanzilb

**Comment by icanzilb** [comment]
yes, a non-swizzling version would handle this precise situation better 👍

**Comment by philipengberg** [comment]
This is starting to create more and more issues with table views

When we just do a regular non-animating

```swift
tableView.reloadSections(IndexSet(integer: 1), with: .none)
```

**all** cells in **all** sections animate their `layoutSubviews` routines. 
Problem is that we are super dependent on EasyAnimation for a central part of the app, that needs `CAAnimation`s and `UIView` animations to work together.

Any immediate plans on a non-swizzling version @icanzilb?
