### ISSUE TITLE
Seems to crash in Xcode7.3 / iOS 9.3

### ISSUE THREAD

**Issue by fireflyexperience** [icanzilb/EasyAnimation#30]
crashes in CALayer extension on

`private static func replaceAnimationMethods() {
        //replace actionForKey
        method_exchangeImplementations(
            class_getInstanceMethod(self, Selector("actionForKey:")),
            class_getInstanceMethod(self, Selector("EA_actionForKey:")))
    }`

EXC_BAD_ACCESS

**Comment by icanzilb** [comment]
I'll give that a try - thanks for reporting

**Comment by icanzilb** [comment]
I tried with both 7.3b2 and 7.3b3 - the demo app works, if you find a problem I can reproduce leave a comment
