### ISSUE TITLE
Error after update to Xcode 7.3

### ISSUE THREAD

**Issue by hevertonrodrigues** [icanzilb/EasyAnimation#34]
![screen shot 2016-03-23 at 10 49 25 am](https://cloud.githubusercontent.com/assets/3950909/13987156/f9eebc98-f0e4-11e5-8429-3595036c48ce.png)

**Comment by icanzilb** [comment]
I'll have to look into updating for 7.3 thanks

**Comment by icanzilb** [comment]
update your pods for a fix

**Comment by hevertonrodrigues** [comment]
you are fast! haha thank you so much :)
