### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by icanzilb** [icanzilb/EasyAnimation#39]
Hey everyone, 

I pulled the Swift 3 branch https://github.com/icanzilb/EasyAnimation/tree/swift3 that was build by PRs so far (thanks again!) and did a conversion to Swift 3 syntax coding session so now the EA methods are concise with the UIKit methods. The demo app works fine (after fixing few things that looks like UIKit bugs in beta 3) but I'd like to get more feedback from ppl if the swift 3 branch works fine in their own projects.

Note that I also added a `EasyAnimation.disableSwizzling()` for the ones who still want to use sequences but don't want to swizzle all methods (recurring topic in this repo).

Thanks, and looking forward to some feedback if you have

**Comment by netgfx** [comment]
Carthage build fails with final XCode 8
```
<unknown>:0: error: no such file or directory: '/Users/milo/Downloads/carthage/Carthage/Checkouts/EasyAnimation/EasyAnimation/EAAnimationDelayed.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```
