### ISSUE TITLE
How to use with Carthage?

### ISSUE THREAD

**Issue by TeenageDev** [icanzilb/EasyAnimation#40]
Hello,
'Installation' mentioned that Carthage is supported. However, when I try to github “EasyAnimation” on my Cartfile, I get an error.

**Comment by icanzilb** [comment]
I would also love to see an example how to do that, so we can include it in the README

**Comment by netgfx** [comment]
yes it fails on the plugin dependencies like many projects
When running `carthage update` for  github "icanzilb/EasyAnimation" "master"|
```
Building scheme "EasyAnimation" in EasyAnimation.xcodeproj
2016-09-14 13:32:35.775 xcodebuild[71550:5961802] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Swimat.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-14 13:32:35.776 xcodebuild[71550:5961802] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **
```

**Comment by icanzilb** [comment]
The error message in your comment is related to uncompatible Xcode plugins - I don't think this is in any way related to `EasyAnimation`

**Comment by netgfx** [comment]
When looking at the .log file it states the following:

```
<unknown>:0: error: no such file or directory: '/Users/milo/Downloads/carthage/Carthage/Checkouts/EasyAnimation/EasyAnimation/EAAnimationDelayed.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

**Comment by josete89** [comment]
The error is when carthage try to build the project:

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by netgfx** [comment]
@josete89 I believe that is the error that you get if the project isn't configured with Swift 3.0, are you using the `swift3` branch or `master`?

**Comment by netgfx** [comment]
@icanzilb It is still throwing an error when build from carthage:

```
<unknown>:0: error: no such file or directory: '/Users/milo/Downloads/carthage/Carthage/Checkouts/EasyAnimation/EasyAnimation/EAAnimationDelayed.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```
It is trying to load the `EAAnimationDelayed.swift` file but it doesn't exist in the repository, it does exist however on the xcode.proj file

**Comment by netgfx** [comment]
Basically you need to replace `EAAnimationDelayed.swift` with `EAAnimationFuture.swift` on the `project.pbxproj` file and it works.

**Comment by icanzilb** [comment]
I changed the README so now it doesn't tell that Cartage is supported. I don't use it and I don't even know how to test it - somebody added it via PR but I can't really support it.

**Comment by netgfx** [comment]
Basically it simply works on your `master` it just needs the change I mentioned above. This change is not only for carthage, it displays an error even when trying to build through XCode. Download the Repository and open the `project.pbxproj` with XCode and you will see the error.
