### ISSUE TITLE
EAAnimationDelayed.swift file missing in xcode 

### ISSUE THREAD

**Issue by okipol88** [icanzilb/EasyAnimation#42]
The file is missing when i either download source in release 1.1.1 (I think 1.1.0 is also affected).

After removal I had to add `EAAnimationFuture.swift` to make the project compile.

**Comment by grEvenX** [comment]
See #43

**Comment by icanzilb** [comment]
#43 this has just been merged - I have no idea myself if that fixes that problem but @grEvenX says it should
