### ISSUE TITLE
Question about "pending:" print statements 

### ISSUE THREAD

**Issue by sahandnayebaziz** [icanzilb/EasyAnimation#45]
Hey, awesome library. I've got a low-priority question. I'm seeing this in my console when dismissing a view controller back to one of my views where I have a collection view with EasyAnimation running in the cells: 

```
pending: bounds from NSRect: {{0, 0}, {0, 0}} to Optional(NSRect: {{0, 0}, {414, 0}})
pending: position from NSPoint: {0, 0} to Optional(NSPoint: {207, 1})
pending: bounds from NSRect: {{0, 0}, {0, 0}} to Optional(NSRect: {{0, 0}, {414, 0}})
pending: position from NSPoint: {0, 0} to Optional(NSPoint: {207, 0})
pending: bounds from NSRect: {{0, 0}, {0, 0}} to Optional(NSRect: {{0, 0}, {8, 13}})
pending: position from NSPoint: {0, 0} to Optional(NSPoint: {402, -0.5})
pending: position from NSPoint: {207, 1} to Optional(NSPoint: {207, 1})
pending: opacity from 1 to Optional(1)
pending: bounds from NSRect: {{0, 0}, {0, 0}} to Optional(NSRect: {{0, 0}, {141.66666666666666, 253}})
pending: position from NSPoint: {0, 0} to Optional(NSPoint: {70.833333333333329, 126.5})
```

I am not so worried about the statements printing, but I'm unsure how to react. Does this necessarily mean I'm misusing animations in some way, or is EasyAnimation just letting me know what's going on?

**Comment by icanzilb** [comment]
This is debug info, it's been fixed - just get the latest pod version next week to get rid of it

**Comment by YotamGolomb** [comment]
Hey,
When is the next release?

**Comment by icanzilb** [comment]
Nothing in particular is scheduled, if I merge any PRs we'll certainly release them

**Comment by YotamGolomb** [comment]
referring to the debug info issue someone stated here , it is still there :)

**Comment by icanzilb** [comment]
oh, I'll look into that, thanks for noticing
