### ISSUE TITLE
Disable aggressive debug logging

### ISSUE THREAD

**Issue by philipengberg** [icanzilb/EasyAnimation#49]
Our console is getting seriously spammed with `pending: bla bla` because of `EasyAnimation:L274`:

```swift
print("pending: \(anim.keyPath) from \(anim.fromValue) to \(anim.layer.value(forKeyPath: anim.keyPath))")
```

Is it possible to either remove it all together or to set a flag that enables/disables this logging?

**Comment by icanzilb** [comment]
Addressed in: https://github.com/icanzilb/EasyAnimation/releases/tag/1.1.2
