### ISSUE TITLE
Warnings: Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

### ISSUE THREAD

**Issue by emilpedersen** [icanzilb/EasyAnimation#51]
I get two warnings:

Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

In EasyAnimation.swift
 - line 85
 - line 148

Xcode 8.3.1

**Comment by icanzilb** [comment]
I'll have to look into this 👌 seems Swift and ObjC might be parting ways soon ?

**Comment by derick182** [comment]
Same warning here. any news?

**Comment by icanzilb** [comment]
Care to create a PR?

**Comment by derick182** [comment]
I'm not sure that I can handle this.

**Comment by ExcaliburAir** [comment]
this?
https://stackoverflow.com/questions/42824541/swift-3-1-deprecates-initialize-how-can-i-achieve-the-same-thing

**Comment by icanzilb** [comment]
addressed in https://github.com/icanzilb/EasyAnimation/releases/tag/2.0.0 thanks for your patience :)
