### ISSUE TITLE
String interpolation produces debug description

### ISSUE THREAD

**Issue by derick182** [icanzilb/EasyAnimation#52]
![2017-04-26_20-18-52](https://cloud.githubusercontent.com/assets/3238557/25449957/b50c829a-2abd-11e7-87f9-95ab81d0e1c4.png)
Can you please check this warning?

**Comment by icanzilb** [comment]
this seems like a Swift 3.1 warnings, do you want to create a PR with a fix?

**Comment by icanzilb** [comment]
This is addressed in https://github.com/icanzilb/EasyAnimation/releases/tag/2.0.0 Thanks!
