### ISSUE TITLE
Doesn't ios8 already have this?

### ISSUE THREAD

**Issue by goktugyil** [icanzilb/EasyAnimation#6]
I've been working with the core iOS methods and the examples you gave in EasyAnimation is the same as standard iOS ones. Am I missing something?

**Comment by icanzilb** [comment]
The very first example in the readme works on iOS8 by default - yes. Or do you mean something else?

**Comment by goktugyil** [comment]
I think the readme isn't clear on what is an iOS default and what EasyAnimation brings to the table

**Comment by fatuhoku** [comment]
Yeah not clear to me at all what EasyAnimation as a library does

**Comment by icanzilb** [comment]
there's a readme ... not sure what more i can do

**Comment by goktugyil** [comment]
The examples are of animateWithDuration which was introduced in iOS4. 

The example says normally its X, but with EasyAnimation its Y.
But in real world normally its Y, so whats the benefit of EasyAnimation?

**Comment by icanzilb** [comment]
read the readme of this repository, thanks

**Comment by goktugyil** [comment]
Yes I read the readme. 

This piece here says that animations without EasyAnimations suck:
http://i.imgur.com/uck5xPA.png

I tried this, it took me 1 minute for this experiment and it doesn't suck:
http://i.imgur.com/06Cuv6W.gif

I didn't need to write the whole

    let anim = CABasicAnimation(keyPath: "position.x")
    anim.fromValue = 100.0
    anim.toValue = 200.0
    anim.duration = 2.0
    view.layer.addAnimation(anim, forKey: nil)

thing as you see in the code. 

So is your readme basically lying? From my point of view what you are saying is exactly like this:

Normal UIView:
let myview = UIView()
myview.thisShouldWork = true
myview.thisIsAView = true
myview.thisViewStartsFromX = 10
myview.thisViewStartsFromY = 10
myview.thisViewWidth = 10
myview.thisViewHeight = 10

Heres EasyView:

let myview = UIView(frame: CGRect(10,10,10,10))

tada, it works yey!!

**Comment by goktugyil** [comment]
If you didn't understand what I say, let me make it more clearer:

Your readme gives me no relevant/true information, its just a useless piece of document.

I haven't checked your code btw, I am just talking about the readme

**Comment by icanzilb** [comment]
dude I answered you 2 months ago - you are right. this piece of code is there for illustrative purpose
