### ISSUE TITLE
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by joeshonm** [icanzilb/EasyAnimation#60]
Just putting a heads up here that I got the error "Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1" after updating the Xcode 9.3 and iOS 11.3 to work with ARKit 1.5.

Hopefully updating the module won't be a big deal to clear up this issue.

**Comment by iKisliy** [comment]
What you mean about "Updating the module"? Looking for solution too

**Comment by joeshonm** [comment]
@iKisliy I see that there was a compiling issue on my end. I cleaned the project and resolved it. Thank you.
