### ISSUE TITLE
Unable to install via CocoaPods?

### ISSUE THREAD

**Issue by bitops** [icanzilb/EasyAnimation#8]
Hey Marin, I'm new to using CocoaPods so maybe I'm just doing something wrong.

Here's my cocoapods gem setup:

```shell
$ gem list cocoapods

*** LOCAL GEMS ***

cocoapods (0.38.0)
cocoapods-core (0.38.0)
cocoapods-downloader (0.9.1)
cocoapods-plugins (0.4.2)
cocoapods-stats (0.5.3)
cocoapods-trunk (0.6.1)
cocoapods-try (0.4.5)
```

And here is my Podfile:

```shell
$ cat Podfile 
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'FooApp' do
  pod 'EasyAnimation'
end

target 'FooAppTests' do
end
```

Finally, here is the output when I run ```pod install``` in my project:

```shell
$ pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `EasyAnimation` required by `Podfile`
```

Any suggestions?

**Comment by icanzilb** [comment]
I'm not sure if you can build iOS 7 apps with Swift ... try compiling for iOS8 instead?

**Comment by pjebs** [comment]
You can. You can't use cocoapods with iOS 7 and swift.

**Comment by bitops** [comment]
@icanzilb I guess @pjebs has the answer. 

@pjebs is there a workaround?

**Comment by pjebs** [comment]
No workaround. Either you don't use cocoapods and install easy animation manually or you change to iOS 8+

**Comment by bitops** [comment]
Bummer. I guess I'll try installing it manually then.
