### ISSUE TITLE
How could I chain animation from different code block?

### ISSUE THREAD

**Issue by iaomw** [icanzilb/EasyAnimation#9]
I need chain the animation from different code block while I have a var of chain. But it didn't work after the chain finished, how could I do it?
```
var animationChain:EAAnimationDelayed = UIView.animateAndChainWithDuration...

func someFunction() {
	
	self.animationChain.animateWithDuration...
}

func anotherFunction() {
	
	self.animationChain.animateWithDuration...
}
```

**Comment by icanzilb** [comment]
Not sure what exactly are you trying to do but here's how you create animation chains:
https://github.com/icanzilb/EasyAnimation#chain-animations

**Comment by iaomw** [comment]
Thanks, I have read that, and that's the main reason for me to try.  The chain looks awesome.

I consider it as something like serial dispatch_queue, it will auto start queue job after the previous job done. I will chain animations dynamically from different places, I really need a chain like that.

If I chain them in the same place, it works. But while I am add animations to it after the previous chained animations finished, It will never start again. The chain looks dead and not reusable once finished. 

If I miss used it, please let me know :)

**Comment by icanzilb** [comment]
I'm not sure if you could use the API in this way ... at least I never intended to have it working like that :) But I'll give it a try when I have a bit of time and see what happens

**Comment by iaomw** [comment]
Thanks, happy to hear your plan, that would be awesome.
